#binop_separator = "Front"
#blank_lines_lower_bound = 1
#blank_lines_upper_bound = 3
#brace_style = "AlwaysNextLine"
#control_brace_style = "AlwaysNextLine"
#combine_control_expr = false
#enum_discrim_align_threshold = 30
#fn_params_layout = "Tall"
#fn_call_width = 60
#fn_single_line = true
force_explicit_abi = true
#force_multiline_blocks = true
#format_code_in_doc_comments = true
#format_generated_files = true
#format_strings = true
hard_tabs = true
tab_spaces = 4
#imports_indent = "Block"
#imports_layout = "Vertical"
#indent_style = "Block"
#license_template_path = ""
#match_arm_blocks = true
match_arm_leading_pipes = "Preserve"
#match_block_trailing_comma = true
max_width = 200
merge_derives = false
#merge_imports = true
newline_style = "Native"
#normalize_comments = false
#normalize_doc_attributes = false
#preserve_block_start_blank_lines = false
#overflow_delimited_expr = false
remove_nested_parens = true
#reorder_impl_items = true
reorder_imports = true
reorder_modules = true
#single_line_if_else_max_width = 0
#space_after_colon = true
#space_before_fn_sig_paren = false
#spaces_around_ranges = true
#space_around_attr_eq = true
#struct_field_align_threshold = 30
#struct_lit_single_line = true
#struct_lit_width = 30
#trailing_comma = "Vertical"
#trailing_semicolon = true
#type_punctuation_density = "Wide"
#unstable_features = false
use_field_init_shorthand = false
use_small_heuristics = "Off"
use_try_shorthand = true
#where_single_line = false
#wrap_comments = true

#ignore = []
